# Generated by Django 5.2.4 on 2025-07-25 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDSPosts', '0002_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создание поста'),
        ),
    ]
