# Generated by Django 5.2.4 on 2025-07-25 10:12

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDSPosts', '0004_alter_transaction_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='operation', chained_model_field='type', on_delete=django.db.models.deletion.PROTECT, to='DDSPosts.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='DDSPosts.subcategory', verbose_name='Подкатегория'),
        ),
    ]
