# Generated by Django 5.2.4 on 2025-07-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDSPosts', '0005_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='create',
            new_name='date',
        ),
    ]
